default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :beta do
    build_app(
      workspace: "MSMEBazaar.xcworkspace",
      scheme: "MSMEBazaar",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
  
  desc "Build and deploy to App Store"
  lane :release do
    build_app(
      workspace: "MSMEBazaar.xcworkspace", 
      scheme: "MSMEBazaar",
      export_method: "app-store"
    )
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false
    )
  end
end

platform :android do
  desc "Build and deploy to Play Console internal testing"
  lane :beta do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/"
    )
    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
  
  desc "Build and deploy to Play Store"
  lane :release do
    gradle(
      task: "bundle", 
      build_type: "Release",
      project_dir: "android/"
    )
    upload_to_play_store(
      track: "production",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end