// /shared/types/feature.ts
export enum Feature {
  ADVANCED_ANALYTICS = "ADVANCED_ANALYTICS",
  CUSTOM_REPORTS = "CUSTOM_REPORTS",
  PRIORITY_SUPPORT = "PRIORITY_SUPPORT",
  PRO_UPGRADE = "PRO_UPGRADE",
  PAYMENTS = "PAYMENTS",
  PAYMENT_HISTORY = "PAYMENT_HISTORY",
  AI_BUSINESS_VALUATION = "AI_BUSINESS_VALUATION",
  COMPLIANCE_CHECKLIST = "COMPLIANCE_CHECKLIST",
  EXIT_STRATEGY = "EXIT_STRATEGY",
  MARKET_LINKAGE = "MARKET_LINKAGE",
  BUSINESS_LOANS = "BUSINESS_LOANS",
  CRM_PIPELINE = "CRM_PIPELINE",
  LEADERSHIP_TRAINING = "LEADERSHIP_TRAINING",
  DEALS_MARKETPLACE = "DEALS_MARKETPLACE",
  ADMIN_FEATURE_TOGGLES = "ADMIN_FEATURE_TOGGLES",
  ADMIN_USER_MANAGEMENT = "ADMIN_USER_MANAGEMENT",
  SUPERADMIN_MONITORING = "SUPERADMIN_MONITORING",
  SUPERADMIN_DATABASE_OPS = "SUPERADMIN_DATABASE_OPS",
  USER_PROFILE = "USER_PROFILE",
  BUSINESS_PROFILE = "BUSINESS_PROFILE",
  BUSINESS_PROFILE_VERIFY = "BUSINESS_PROFILE_VERIFY",
  MSME_NETWORKING = "MSME_NETWORKING",
  B2B_MARKETPLACE = "B2B_MARKETPLACE",
  MESSAGING = "MESSAGING",
  ORDERS_MANAGEMENT = "ORDERS_MANAGEMENT",
  RECOMMENDATIONS = "RECOMMENDATIONS",
  MATCHMAKING = "MATCHMAKING",
  SEARCHMSME = "SEARCHMSME",
  SEARCHMATCHMAKING = "SEARCHMATCHMAKING",
  ADMIN_SERVICES = "ADMIN_SERVICES",
  SUPER_ADMIN_SERVICES = "SUPER_ADMIN_SERVICES",
  AGENT_SERVICES = "AGENT_SERVICES",
  INVESTOR_SERVICES = "INVESTOR_SERVICES",
  LOAN_SERVICES = "LOAN_SERVICES",
  BUYER_SERVICES = "BUYER_SERVICES",
  SELLER_SERVICES = "SELLER_SERVICES"
}

export enum UserRole {
  ADMIN = "admin",
  SUPER_ADMIN = "super_admin",
  MSME_OWNER = "msmeOwner",
  SELLER = "seller",
  BUYER = "buyer",
  AGENT = "agent",
  INVESTOR = "investor",
  DEVELOPER = "developer"
}

export enum AccessLevel {
  READ = "READ",
  WRITE = "WRITE",
  ADMIN = "ADMIN"
}

export interface FeatureMeta {
  label: string;
  description: string;
  enabled: boolean;
  proOnly?: boolean;
  rolesEnabled?: UserRole[];
  accessLevel?: AccessLevel;
  rolloutPercentage?: number;
  expiry?: string;
  availableRegions?: string[];
}
